refactor: conditionally run based on the package manager (#1205)
* refactor: conditionally run based on the package manager

* Update pre-push

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -17,10 +17,19 @@ check_pnpm_files() {
 }
 
 # List of all check functions
-CHECK_FUNCTIONS=(
-  "check_npm_files"
+# Detect the lock file to determine the package manager
+if [ -f "pnpm-lock.yaml" ]; then
+  CHECK_FUNCTIONS=(
   "check_pnpm_files"
 )
+elif [ -f "package-lock.json" ]; then
+  CHECK_FUNCTIONS=(
+	"check_npm_files"
+  )
+else
+  echo "No lock file detected for pnpm or npm. Aborting pre-push checks."
+  exit 1
+fi
 
 # Check for changes in specified files before pushing and run corresponding commands
 ## Get the upstream branch
@@ -37,18 +46,18 @@ if [ -z "$UPSTREAM" ]; then
 fi
 
 ## Get the list of files changed between upstream and HEAD
-FILES=$(git diff --name-only $UPSTREAM..HEAD)
+FILES=$(git diff --name-only "$UPSTREAM"..HEAD)
 
 ## Check each pattern and run corresponding command
 for check_function in "${CHECK_FUNCTIONS[@]}"; do
   # Call the check function to set variables
   $check_function
-  
+
   if echo "$FILES" | grep -qE "$PATTERN"; then
     echo "Detected changes in $DESCRIPTION"
 
     ## Run the corresponding command
-    eval "$COMMAND"
+    $COMMAND
 
     if [ $? -ne 0 ]; then
       echo "Command failed: $COMMAND. Aborting push."
