fix: checks-done step must succeed (#329)

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -28,10 +28,21 @@ jobs:
     needs: [init]
 
   checks-done:
+    if: ${{ always() }}
     runs-on: ubuntu-latest
     steps:
       - name: 🎉 Checks done
-        run: echo "🎉 All tests & build were successful."
+        run: |
+          resultBuild="${{ needs.build.result }}"
+          resultTest="${{ needs.test.result }}"
+          resultLint="${{ needs.lint.result }}"
+          if [[ $resultBuild == "success" && $resultTest == "success" && $resultLint == "success" ]]; then
+            echo "🎉 All tests & build were successful."
+            exit 0
+          else
+            echo "Some tests were failing."
+            exit 1
+          fi
     needs: [build, test, lint]
 
   deploy:
